SocialDistribution/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions
    
schema_view = get_schema_view(
    openapi.Info(
        title="social distribution API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('admin/', admin.site.urls),
    path('service/',include("service.urls")),
    path('',include("login.urls")),
    path('',include("authors.urls")),
    path('',include("post.urls")),
    path('',include('me.urls')), 
    path('',include('inbox.urls')), 
]



login/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.log_in, name="login"),
    path("login/", views.log_in, name="login"),
    path("signup/", views.sign_up, name="signup")
    
]

me/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path("authors/<str:userId>/profile", views.my_profile,name="profile-page"),
    path("authors/<str:userId>/profile/<str:postId>", views.my_profile_modify,name="modify-post-page"),
    path("authors/<str:userId>/information", views.myinfo,name="information-page"),
    
    path("authors/<str:userId>/informationedit", views.myinfoedit,name="informationedit-page"),

]

authors/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.contrib.auth.models import AbstractBaseUser
import uuid

# Create your models here.
class single_author(AbstractBaseUser):
    type = "author"
    username = models.CharField(primary_key=True,unique=True,max_length=255,default='')
    password = models.CharField(validators=[MinLengthValidator(6)],max_length=255,default='')
    uuid= models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    id = models.CharField(unique=True,max_length=255,blank=True,null=True)
    host = models.CharField(max_length=255,default='',blank=True)
    display_name = models.CharField(max_length=255,blank=True,default='')
    url = models.URLField(blank=True,default='')
    github = models.URLField(blank=True,default='')
    profileImage = models.ImageField(upload_to='avatars/', blank=True,null=True)

    USERNAME_FIELD = 'username'

    # create a unique id for each new user
    # def generate_unique_id(self):
    #     unique_id = uuid.uuid4()
    
    def __str__(self):
        return 'type:'+self.type+ 'id:'+ self.id+'host:'+ self.host+'display_name'+ self.display_name+'url'+ self.url+'github'+ self.github

class FollowRequest(models.Model):
    type = "Follow"
    summary = models.TextField(max_length=25, blank=True,default='')
    actor = models.ForeignKey(to=single_author,on_delete=models.CASCADE,related_name='request_sender')
    object = models.ForeignKey(to=single_author,on_delete=models.CASCADE,related_name='request_receiver')

# class followPerson(models.Model):
#     username = models.CharField(max_length=255, blank=True,default='')
#     authorId = models.CharField(max_length=255, blank=True,default='')

class Followers(models.Model):
    type = "followers"
    author = models.ForeignKey(single_author, on_delete=models.CASCADE, related_name="all_authors")
    follower = models.ForeignKey(single_author, on_delete=models.CASCADE, related_name="all_followers")


class ExternalFollowers(models.Model):
    author = models.ForeignKey(single_author, on_delete=models.CASCADE, related_name="externalAuthors")
    groupNumber = models.IntegerField(default=0)
    external_username = models.CharField(max_length=255, blank=True)
    external_id = models.CharField(max_length=255,blank=False,null=False)

login/models.py
from django.db import models
        

login/forms.py
from django import forms
from authors.models import single_author
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(forms.ModelForm):
    # username = forms.CharField(max_length=255)
    # password = forms.CharField(max_length=255)
    class Meta:
        model = single_author
        fields = ['display_name','github','profileImage']

class newUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','password1','password2']

class LoginForm(forms.ModelForm):
    class Meta:
        model = single_author
        fields = ['username', 'password']

login/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.http import HttpResponseRedirect
from authors.models import single_author,Followers
from django.urls import reverse
from .forms import SignUpForm
from .forms import LoginForm
from .forms import newUserForm
from django.contrib.auth.models import User
from inbox.models import Inbox

import uuid
# Create your views here.
def log_in(request):
    #login by username and password
    displayConfirmMsg = False
    if request.method == 'POST':
        form = LoginForm()
        username = request.POST['username']
        password = request.POST['password']

        try:
            userLogin = User.objects.get(username = username)
        except:
            return HttpResponse("Username does not exist")

        if userLogin.is_active == False:
            displayConfirmMsg = True
            return render(request,"login/login.html",{
                "form":form,
                "display":displayConfirmMsg
                }) 


        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request,user)
            current_user = request.user
            current_authorId = single_author.objects.get(username=current_user).uuid

            # every account needs an inbox model
            current_author = single_author.objects.get(uuid=current_authorId)
            if not Inbox.objects.filter(author=current_author).exists():
                Inbox.objects.create(author=current_author)


            
            return HttpResponseRedirect(reverse("home-page",args=[current_authorId]))
        else:
            return render(request,"login/login.html",{
                "username":None,
                "password":None,
                "form":form,
                "display":displayConfirmMsg
    
            })
        # if single_author.objects.filter(username=username).exists():
        #     password = request.POST.get('password')
        #     storedUser = single_author.objects.get(username=username)
        #     storedUserPassword = storedUser.password
        #     userId = storedUser.id
        #     # if storedUserPassword == password:
        #     #     #redirect this for now
        #     #     # return HttpResponseRedirect("post/index.html",{
        #     #     #     'username':storedUser
        #     #     # })
        #     #     # return HttpResponseRedirect("")
        #     #     return HttpResponseRedirect(reverse("home-page",args=[userId]))
        #     # else:
        #     #     form = LoginForm()
        #     #     isNotPasswordMatch = True
        #     #     return render(request, 'login/login.html',{
        #     #         "form":form,
        #     #         'isNotPasswordMatch':isNotPasswordMatch
        #     #     })
        # else:
        #     form = LoginForm()
        #     isNotUsernameExist = True
        #     return render(request, 'login/login.html',{
        #         "form":form,
        #         'isNotUsernameExist':isNotUsernameExist
        #     })
    else:
        form = LoginForm()

    return render(request,"login/login.html",{
        "form":form,
        "display":displayConfirmMsg
    })

def sign_up(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST,request.FILES)
        userForm = newUserForm(request.POST)
        if form.is_valid() and userForm.is_valid():
            new_author = form.save(commit=False)
            # generate something
            authorHost = request.META.get('HTTP_HOST')
            authorId = f"{request.build_absolute_uri('/')}service/authors/{new_author.uuid}"
            authorUrl = f"{request.build_absolute_uri('/')}service/authors/{new_author.uuid}"
            new_user = userForm.save(commit=False)
            #### Needs Admin Permission to activate this new account ####
            new_user.is_active = False
            
            #######################
            new_author.username = userForm.cleaned_data['username']
            new_author.password = userForm.cleaned_data['password1']
            new_author.id = authorId
            new_author.host = authorHost
            new_author.url = authorUrl
            new_author.save()
            new_user.save()
            #######################
            
            return HttpResponseRedirect(reverse('login'))
    else:
        form = SignUpForm()
        userForm = newUserForm()

    return render(request,"login/signup.html",{
        'form':form,
        'newUser':userForm
    })

login/templates/login/login.html
{% extends 'base.html' %} {% load static %} {%block title%} Log In {%endblock%}
{%block css_files%} <link rel="stylesheet" href="{% static "login/login.css"%}">{%endblock%} {% block header %} {% endblock %}
{% block content %}
<div class="d-flex align-items-center justify-content-center">
  
  <body class="vh-100 gradient-custom">
    <div class="container">
      <div
        class="row d-flex justify-content-center align-items-center h-100"
        style="
          border: solid 1px rgba(255, 255, 255, 0.5);
          border-radius: 20px;
          width: 40%;
        "
      >
        <div class="col-xl-5">
          <div
            class="card bg-dark text-white"
            style="border-radius: 1rem; text-align: center"
          >
            <div class="card-body p-5 text-center">
              <div class="mb-md-5 mt-md-4 pb-5">
                <h1 class="fw-bold mb-2">Welcome to SocialDistribution!</h1>
                <p class="text-white-50 mb-5">
                  Please enter your username and password!
                </p>

                {% if display %}
                <p>This account is not approved to be activated, please contact admin.</p>
                {% endif %}

                <form method="post">
                  {%csrf_token%}

                  <!-- add this new code for the login input-->
                  <div class="login_info">
                    <label for="Username">Username:</label>
                    <input
                      type="username"
                      class="form-control"
                      placeholder="Enter username"
                      name="username"
                      style="
                        background-color: transparent;
                        border: 0;
                        width: 90%;
                        margin-left: 5%;
                      "
                    />
                    <label for="Password">Password:</label>
                    <input
                      type="password"
                      class="form-control"
                      placeholder="Enter password"
                      name="password"
                      style="
                        background-color: transparent;
                        border: 0;
                        width: 90%;
                        margin-left: 5%;
                      "
                    />
                  </div>

                  <!--deleted this codes
                        <div class="form-outline form-white mb-4" style = "font-family: 'Lucida Console';">
                            {{ form }}
                        </div>
                      -->

                  <button
                    class="btn btn-outline-light btn-lg px-5"
                    type="submit"
                    style="
                      background-color: transparent;
                      border: solid 1px rgb(255, 255, 255);
                    "
                  >
                    Login
                  </button>
                </form>
              </div>

              <div>
                <p class="mb-0">
                  Don't have an account?
                  <a href={% url "signup" %} class="text-white-50 fw-bold"
                    >Sign Up Here</a>
                  
                </p>
              </div>
              <button onclick="darkMode()">Darkmode</button>
              <button onclick="lightMode()">LightMode</button>
            
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>

  <script>
      function darkMode() {
        var element = document.body;
       
        element.className = "dark-mode";
       
      }
      function lightMode() {
        var element = document.body;
      
        element.className = "gradient-custom";
        
      }
    </script>
</div>
{% endblock %}

login/templates/login/signup.html
{% extends 'base.html' %} 
{% load static %} 

{%block title%} Sign Up {%endblock%} 
{%block css_files%}<link rel="stylesheet" href="{% static "login/signup.css"%}">{%endblock%}

{% block header%}
{% comment %} <div class="container-fluid" style="height: 200px; background-color: pink">
  <h1>Sign Up Page</h1>
</div> {% endcomment %}
{% endblock %}
{% block content %}

<body class="backgroundcolor">
  <section class="background">
  <h2 class="">Create an account</h2>

    <p>Please note that if you are a new user, you will be waited to be approved by admins to activate your account</p>
    <form method="POST" enctype="multipart/form-data" style='display: table;'>
      {%csrf_token%}
      <div class="">
        <div class="">

          <label style='display: table-cell;' for="id_username">Username:</label>
          <input style='display: table-cell;' type="text" name="username" maxlength="150" autofocus="" required="" id="id_username">
          <br>
          <!-- <span class="helptext">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</span> -->
          <label style='display: table-cell;' for="id_password1">Password:</label>
          <input style='display: table-cell;' type="password" name="password1" autocomplete="new-password" required="" id="id_password1">
          <br>
          <!-- <span class="helptext"><ul><li>Your password can’t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can’t be a commonly used password.</li><li>Your password can’t be entirely numeric.</li></ul></span> -->
          <label style='display: table-cell;' for="id_password2">Password confirmation:</label>
          <input style='display: table-cell;' type="password" name="password2" autocomplete="new-password" required="" id="id_password2">
          <br>
          <!-- <span class="helptext">Enter the same password as before, for verification.</span> -->
          <label style='display: table-cell;' for="id_display_name">Display name:</label>
          <input style='display: table-cell;' type="text" name="display_name" maxlength="255" id="id_display_name"><br>
          <label style='display: table-cell;' for="id_github">Github:</label>
          <input style='display: table-cell;' type="url" name="github" maxlength="200" id="id_github"><br>
          <label style='display: table-cell;' for="id_profileImage">ProfileImage:</label>
          <input style='display: table-cell;' type="file" name="profileImage" accept="image/*" id="id_profileImage"><br>

          <button type="submit">Register</button>
        </div>

      </div>
    </form>
    <button onclick="darkMode()">Darkmode</button>
    <button onclick="lightMode()">LightMode</button>


  </section>
</body>
  <script>
      function darkMode() {
        var element = document.body;
       
        element.className = "dark-mode";
       
      }
      function lightMode() {
        var element = document.body;
      
        element.className = "backgroundcolor";
        
      }
    </script>

{% endblock %}